"""Updated pages table

Revision ID: 30e5371c45d4
Revises: 1d0360cef4bd
Create Date: 2024-04-14 20:57:57.972438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '30e5371c45d4'
down_revision: Union[str, None] = '1d0360cef4bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'store_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pages', 'store_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
