"""Updated Auth Table

Revision ID: 7452e7b79a64
Revises: 2f1afb2e8459
Create Date: 2024-04-14 15:07:30.844129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7452e7b79a64'
down_revision: Union[str, None] = '2f1afb2e8459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authentications', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authentications', type_='unique')
    # ### end Alembic commands ###
